sick_tim_561_ros_driver:
  ros__parameters:
    frame_id: "base_laser_link"
    min_ang: -2.35619 # !degrees -135 (not supported)
    max_ang:  2.35619 # !degrees  135 (not supported)
    intensity: true
    range_max: 25.0
